#!/bin/sh

# Get the directory of the script
SCRIPT_DIR="$(dirname "$0")"

# Run the Ruby script with modified arguments
ARGS=()
for arg in "$@"; do
  if echo "$arg" | grep -qE '^-[A-Za-z]+'; then
    ARGS+=("--${arg#-}")
  else
    ARGS+=("$arg")
  fi
done

/usr/bin/env ruby "$SCRIPT_DIR/convert.rb" "${ARGS[@]}"
